// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: directories.sql

package db

import (
	"context"
)

const createDirectory = `-- name: CreateDirectory :one
INSERT INTO directories (id, name, prefix, description, uploaded_by)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, prefix, description, uploaded_by, created_at, updated_at
`

type CreateDirectoryParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Prefix      string `json:"prefix"`
	Description string `json:"description"`
	UploadedBy  string `json:"uploaded_by"`
}

func (q *Queries) CreateDirectory(ctx context.Context, arg CreateDirectoryParams) (Directory, error) {
	row := q.db.QueryRowContext(ctx, createDirectory,
		arg.ID,
		arg.Name,
		arg.Prefix,
		arg.Description,
		arg.UploadedBy,
	)
	var i Directory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.Description,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDirectory = `-- name: DeleteDirectory :exec
DELETE FROM directories WHERE id = ?
`

func (q *Queries) DeleteDirectory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDirectory, id)
	return err
}

const getDirectory = `-- name: GetDirectory :one
SELECT id, name, prefix, description, uploaded_by, created_at, updated_at FROM directories WHERE id = ? LIMIT 1
`

func (q *Queries) GetDirectory(ctx context.Context, id string) (Directory, error) {
	row := q.db.QueryRowContext(ctx, getDirectory, id)
	var i Directory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.Description,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDirectories = `-- name: ListDirectories :many
SELECT id, name, prefix, description, uploaded_by, created_at, updated_at FROM directories ORDER BY created_at DESC
`

func (q *Queries) ListDirectories(ctx context.Context) ([]Directory, error) {
	rows, err := q.db.QueryContext(ctx, listDirectories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Directory{}
	for rows.Next() {
		var i Directory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Description,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
