// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, name, description, language, size, blob_path, sha256, uploaded_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, language, size, blob_path, sha256, uploaded_by, created_at, updated_at
`

type CreateFileParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Language    string `json:"language"`
	Size        int64  `json:"size"`
	BlobPath    string `json:"blob_path"`
	Sha256      string `json:"sha256"`
	UploadedBy  string `json:"uploaded_by"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Language,
		arg.Size,
		arg.BlobPath,
		arg.Sha256,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Language,
		&i.Size,
		&i.BlobPath,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, name, description, language, size, blob_path, sha256, uploaded_by, created_at, updated_at FROM files
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetFile(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Language,
		&i.Size,
		&i.BlobPath,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, name, description, language, size, blob_path, sha256, uploaded_by, created_at, updated_at FROM files
ORDER BY created_at DESC
`

func (q *Queries) ListFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Language,
			&i.Size,
			&i.BlobPath,
			&i.Sha256,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByLanguage = `-- name: ListFilesByLanguage :many
SELECT id, name, description, language, size, blob_path, sha256, uploaded_by, created_at, updated_at FROM files
WHERE language = ?
ORDER BY created_at DESC
`

func (q *Queries) ListFilesByLanguage(ctx context.Context, language string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByLanguage, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Language,
			&i.Size,
			&i.BlobPath,
			&i.Sha256,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFile = `-- name: UpdateFile :one
UPDATE files
SET
    name        = ?,
    description = ?,
    language    = ?,
    size        = ?,
    blob_path   = ?,
    sha256      = ?,
    uploaded_by = ?,
    updated_at  = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
RETURNING id, name, description, language, size, blob_path, sha256, uploaded_by, created_at, updated_at
`

type UpdateFileParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Language    string `json:"language"`
	Size        int64  `json:"size"`
	BlobPath    string `json:"blob_path"`
	Sha256      string `json:"sha256"`
	UploadedBy  string `json:"uploaded_by"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFile,
		arg.Name,
		arg.Description,
		arg.Language,
		arg.Size,
		arg.BlobPath,
		arg.Sha256,
		arg.UploadedBy,
		arg.ID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Language,
		&i.Size,
		&i.BlobPath,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
