// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, path, file_name, dir_id, dir_prefix, description, language, size, blob_path, sha256, uploaded_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, path, file_name, dir_id, dir_prefix, description, language, size, blob_path, sha256, uploaded_by, version, created_at, updated_at
`

type CreateFileParams struct {
	ID          string  `json:"id"`
	Path        string  `json:"path"`
	FileName    string  `json:"file_name"`
	DirID       *string `json:"dir_id"`
	DirPrefix   string  `json:"dir_prefix"`
	Description string  `json:"description"`
	Language    string  `json:"language"`
	Size        int64   `json:"size"`
	BlobPath    string  `json:"blob_path"`
	Sha256      string  `json:"sha256"`
	UploadedBy  string  `json:"uploaded_by"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ID,
		arg.Path,
		arg.FileName,
		arg.DirID,
		arg.DirPrefix,
		arg.Description,
		arg.Language,
		arg.Size,
		arg.BlobPath,
		arg.Sha256,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.FileName,
		&i.DirID,
		&i.DirPrefix,
		&i.Description,
		&i.Language,
		&i.Size,
		&i.BlobPath,
		&i.Sha256,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, path, file_name, dir_id, dir_prefix, description, language, size, blob_path, sha256, uploaded_by, version, created_at, updated_at FROM files WHERE id = ? LIMIT 1
`

func (q *Queries) GetFile(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.FileName,
		&i.DirID,
		&i.DirPrefix,
		&i.Description,
		&i.Language,
		&i.Size,
		&i.BlobPath,
		&i.Sha256,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFileIDsForDir = `-- name: ListFileIDsForDir :many
SELECT id FROM files WHERE dir_id = ?
`

func (q *Queries) ListFileIDsForDir(ctx context.Context, dirID *string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFileIDsForDir, dirID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiles = `-- name: ListFiles :many
SELECT id, path, file_name, dir_id, dir_prefix, description, language, size, blob_path, sha256, uploaded_by, version, created_at, updated_at FROM files ORDER BY created_at DESC
`

func (q *Queries) ListFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FileName,
			&i.DirID,
			&i.DirPrefix,
			&i.Description,
			&i.Language,
			&i.Size,
			&i.BlobPath,
			&i.Sha256,
			&i.UploadedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByDir = `-- name: ListFilesByDir :many
SELECT id, path, file_name, dir_id, dir_prefix, description, language, size, blob_path, sha256, uploaded_by, version, created_at, updated_at FROM files WHERE dir_id = ? ORDER BY path ASC
`

func (q *Queries) ListFilesByDir(ctx context.Context, dirID *string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByDir, dirID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FileName,
			&i.DirID,
			&i.DirPrefix,
			&i.Description,
			&i.Language,
			&i.Size,
			&i.BlobPath,
			&i.Sha256,
			&i.UploadedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByLanguage = `-- name: ListFilesByLanguage :many
SELECT id, path, file_name, dir_id, dir_prefix, description, language, size, blob_path, sha256, uploaded_by, version, created_at, updated_at FROM files WHERE language = ? ORDER BY created_at DESC
`

func (q *Queries) ListFilesByLanguage(ctx context.Context, language string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByLanguage, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FileName,
			&i.DirID,
			&i.DirPrefix,
			&i.Description,
			&i.Language,
			&i.Size,
			&i.BlobPath,
			&i.Sha256,
			&i.UploadedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesNoDir = `-- name: ListFilesNoDir :many
SELECT id, path, file_name, dir_id, dir_prefix, description, language, size, blob_path, sha256, uploaded_by, version, created_at, updated_at FROM files WHERE dir_id IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListFilesNoDir(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesNoDir)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FileName,
			&i.DirID,
			&i.DirPrefix,
			&i.Description,
			&i.Language,
			&i.Size,
			&i.BlobPath,
			&i.Sha256,
			&i.UploadedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFile = `-- name: UpdateFile :one
UPDATE files
SET path        = ?,
    file_name   = ?,
    description = ?,
    language    = ?,
    size        = ?,
    blob_path   = ?,
    sha256      = ?,
    uploaded_by = ?,
    updated_at  = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
RETURNING id, path, file_name, dir_id, dir_prefix, description, language, size, blob_path, sha256, uploaded_by, version, created_at, updated_at
`

type UpdateFileParams struct {
	Path        string `json:"path"`
	FileName    string `json:"file_name"`
	Description string `json:"description"`
	Language    string `json:"language"`
	Size        int64  `json:"size"`
	BlobPath    string `json:"blob_path"`
	Sha256      string `json:"sha256"`
	UploadedBy  string `json:"uploaded_by"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFile,
		arg.Path,
		arg.FileName,
		arg.Description,
		arg.Language,
		arg.Size,
		arg.BlobPath,
		arg.Sha256,
		arg.UploadedBy,
		arg.ID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.FileName,
		&i.DirID,
		&i.DirPrefix,
		&i.Description,
		&i.Language,
		&i.Size,
		&i.BlobPath,
		&i.Sha256,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileContent = `-- name: UpdateFileContent :one
UPDATE files
SET blob_path   = ?,
    sha256      = ?,
    size        = ?,
    version     = ?,
    uploaded_by = ?,
    updated_at  = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
RETURNING id, path, file_name, dir_id, dir_prefix, description, language, size, blob_path, sha256, uploaded_by, version, created_at, updated_at
`

type UpdateFileContentParams struct {
	BlobPath   string `json:"blob_path"`
	Sha256     string `json:"sha256"`
	Size       int64  `json:"size"`
	Version    int64  `json:"version"`
	UploadedBy string `json:"uploaded_by"`
	ID         string `json:"id"`
}

// Updates blob content and bumps version number. Called after snapshotting.
func (q *Queries) UpdateFileContent(ctx context.Context, arg UpdateFileContentParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFileContent,
		arg.BlobPath,
		arg.Sha256,
		arg.Size,
		arg.Version,
		arg.UploadedBy,
		arg.ID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.FileName,
		&i.DirID,
		&i.DirPrefix,
		&i.Description,
		&i.Language,
		&i.Size,
		&i.BlobPath,
		&i.Sha256,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
