// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"
	"strings"
)

const countFiles = `-- name: CountFiles :one
SELECT COUNT(*) FROM files
`

func (q *Queries) CountFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilesByPrefix = `-- name: CountFilesByPrefix :one
SELECT COUNT(*) FROM files WHERE path LIKE ? || '%'
`

func (q *Queries) CountFilesByPrefix(ctx context.Context, dollar_1 *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFilesByPrefix, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, path, file_name, description, language, size, sha256, uploaded_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, path, file_name, description, language, size, sha256, uploaded_by, version, created_at, updated_at
`

type CreateFileParams struct {
	ID          string `json:"id"`
	Path        string `json:"path"`
	FileName    string `json:"file_name"`
	Description string `json:"description"`
	Language    string `json:"language"`
	Size        int64  `json:"size"`
	Sha256      string `json:"sha256"`
	UploadedBy  string `json:"uploaded_by"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ID,
		arg.Path,
		arg.FileName,
		arg.Description,
		arg.Language,
		arg.Size,
		arg.Sha256,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.FileName,
		&i.Description,
		&i.Language,
		&i.Size,
		&i.Sha256,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const deleteFiles = `-- name: DeleteFiles :exec
DELETE FROM files WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteFiles(ctx context.Context, ids []string) error {
	query := deleteFiles
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteFilesByPrefix = `-- name: DeleteFilesByPrefix :exec
DELETE FROM files WHERE path LIKE ? || '%'
`

func (q *Queries) DeleteFilesByPrefix(ctx context.Context, dollar_1 *string) error {
	_, err := q.db.ExecContext(ctx, deleteFilesByPrefix, dollar_1)
	return err
}

const getFiles = `-- name: GetFiles :many
SELECT id, path, file_name, description, language, size, sha256, uploaded_by, version, created_at, updated_at FROM files
WHERE id IN (/*SLICE:ids*/?)
ORDER BY path ASC
`

func (q *Queries) GetFiles(ctx context.Context, ids []string) ([]File, error) {
	query := getFiles
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FileName,
			&i.Description,
			&i.Language,
			&i.Size,
			&i.Sha256,
			&i.UploadedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByPath = `-- name: GetFilesByPath :many
SELECT id, path, file_name, description, language, size, sha256, uploaded_by, version, created_at, updated_at FROM files
WHERE path IN (/*SLICE:paths*/?)
ORDER BY path ASC
`

func (q *Queries) GetFilesByPath(ctx context.Context, paths []string) ([]File, error) {
	query := getFilesByPath
	var queryParams []interface{}
	if len(paths) > 0 {
		for _, v := range paths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:paths*/?", strings.Repeat(",?", len(paths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:paths*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FileName,
			&i.Description,
			&i.Language,
			&i.Size,
			&i.Sha256,
			&i.UploadedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctDirs = `-- name: ListDistinctDirs :many
SELECT DISTINCT substr(path, 1, instr(path, '/') - 1) AS dir
FROM files
WHERE instr(path, '/') > 0
ORDER BY dir ASC
`

func (q *Queries) ListDistinctDirs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctDirs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var dir string
		if err := rows.Scan(&dir); err != nil {
			return nil, err
		}
		items = append(items, dir)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiles = `-- name: ListFiles :many
SELECT DISTINCT f.id, f.path, f.file_name, f.description, f.language, f.size, f.sha256, f.uploaded_by, f.version, f.created_at, f.updated_at
FROM files f
LEFT JOIN file_tags ft ON ft.file_id = f.id
LEFT JOIN tags      t  ON t.id = ft.tag_id
WHERE (?1 IS NULL OR f.path     LIKE ?1 || '%')
  AND (?2    IS NULL OR t.name    =     ?2)
  AND (?3   IS NULL OR f.language =    ?3)
ORDER BY f.path ASC
`

type ListFilesParams struct {
	Prefix interface{} `json:"prefix"`
	Tag    interface{} `json:"tag"`
	Lang   interface{} `json:"lang"`
}

// ListFiles is the single entry point for querying files.
// Pass NULL for any filter you want to ignore.
// prefix: path LIKE prefix || '%'   e.g. 'nginx/'
// tag   : join on tags.name         e.g. 'prod'
// lang  : language =                e.g. 'bash'
func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFiles, arg.Prefix, arg.Tag, arg.Lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FileName,
			&i.Description,
			&i.Language,
			&i.Size,
			&i.Sha256,
			&i.UploadedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFile = `-- name: MoveFile :one
UPDATE files
SET path       = ?,
    file_name  = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
RETURNING id, path, file_name, description, language, size, sha256, uploaded_by, version, created_at, updated_at
`

type MoveFileParams struct {
	Path     string `json:"path"`
	FileName string `json:"file_name"`
	ID       string `json:"id"`
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, moveFile, arg.Path, arg.FileName, arg.ID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.FileName,
		&i.Description,
		&i.Language,
		&i.Size,
		&i.Sha256,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileContent = `-- name: UpdateFileContent :one
UPDATE files
SET sha256 = ?,
    size        = ?,
    version     = ?,
    uploaded_by = ?,
    updated_at  = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
RETURNING id, path, file_name, description, language, size, sha256, uploaded_by, version, created_at, updated_at
`

type UpdateFileContentParams struct {
	Sha256     string `json:"sha256"`
	Size       int64  `json:"size"`
	Version    int64  `json:"version"`
	UploadedBy string `json:"uploaded_by"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateFileContent(ctx context.Context, arg UpdateFileContentParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFileContent,
		arg.Sha256,
		arg.Size,
		arg.Version,
		arg.UploadedBy,
		arg.ID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.FileName,
		&i.Description,
		&i.Language,
		&i.Size,
		&i.Sha256,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileMeta = `-- name: UpdateFileMeta :one
UPDATE files
SET description = ?,
    language    = ?,
    updated_at  = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
RETURNING id, path, file_name, description, language, size, sha256, uploaded_by, version, created_at, updated_at
`

type UpdateFileMetaParams struct {
	Description string `json:"description"`
	Language    string `json:"language"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateFileMeta(ctx context.Context, arg UpdateFileMetaParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFileMeta, arg.Description, arg.Language, arg.ID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.FileName,
		&i.Description,
		&i.Language,
		&i.Size,
		&i.Sha256,
		&i.UploadedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
