// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package db

import (
	"context"
)

const countVersionsForFile = `-- name: CountVersionsForFile :one
SELECT COUNT(*) FROM versions WHERE file_id = ?
`

func (q *Queries) CountVersionsForFile(ctx context.Context, fileID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVersionsForFile, fileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (from_host, to_host, file_path, size, duration_ms)
VALUES (?, ?, ?, ?, ?)
RETURNING id, from_host, to_host, file_path, size, duration_ms, created_at
`

type CreateTransferParams struct {
	FromHost   string `json:"from_host"`
	ToHost     string `json:"to_host"`
	FilePath   string `json:"file_path"`
	Size       int64  `json:"size"`
	DurationMs int64  `json:"duration_ms"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.FromHost,
		arg.ToHost,
		arg.FilePath,
		arg.Size,
		arg.DurationMs,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromHost,
		&i.ToHost,
		&i.FilePath,
		&i.Size,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
SELECT COALESCE(MAX(version), 0) FROM versions WHERE file_id = ?
`

func (q *Queries) GetLatestVersionNumber(ctx context.Context, fileID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersionNumber, fileID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getMinVersionToKeep = `-- name: GetMinVersionToKeep :one
SELECT COALESCE(MIN(version), 0)
FROM (
    SELECT version FROM versions
    WHERE file_id = ?
    ORDER BY version DESC
    LIMIT ?
) AS kept
`

type GetMinVersionToKeepParams struct {
	FileID string `json:"file_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) GetMinVersionToKeep(ctx context.Context, arg GetMinVersionToKeepParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMinVersionToKeep, arg.FileID, arg.Limit)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getVersion = `-- name: GetVersion :one
SELECT id, file_id, version, sha256, size, uploaded_by, message, created_at FROM versions WHERE file_id = ? AND version = ?
`

type GetVersionParams struct {
	FileID  string `json:"file_id"`
	Version int64  `json:"version"`
}

// GetVersion gets a specific version of a file.
// version: the version number to get
func (q *Queries) GetVersion(ctx context.Context, arg GetVersionParams) (Version, error) {
	row := q.db.QueryRowContext(ctx, getVersion, arg.FileID, arg.Version)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Version,
		&i.Sha256,
		&i.Size,
		&i.UploadedBy,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listPrunableVersions = `-- name: ListPrunableVersions :many
SELECT sha256, version FROM versions
WHERE file_id = ?
  AND version < ?
`

type ListPrunableVersionsParams struct {
	FileID  string `json:"file_id"`
	Version int64  `json:"version"`
}

type ListPrunableVersionsRow struct {
	Sha256  string `json:"sha256"`
	Version int64  `json:"version"`
}

func (q *Queries) ListPrunableVersions(ctx context.Context, arg ListPrunableVersionsParams) ([]ListPrunableVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPrunableVersions, arg.FileID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrunableVersionsRow{}
	for rows.Next() {
		var i ListPrunableVersionsRow
		if err := rows.Scan(&i.Sha256, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollbackVersions = `-- name: ListRollbackVersions :many
SELECT id, file_id, version, sha256, size, uploaded_by, message, created_at FROM versions
WHERE file_id = ?
  AND version > ?
`

type ListRollbackVersionsParams struct {
	FileID  string `json:"file_id"`
	Version int64  `json:"version"`
}

func (q *Queries) ListRollbackVersions(ctx context.Context, arg ListRollbackVersionsParams) ([]Version, error) {
	rows, err := q.db.QueryContext(ctx, listRollbackVersions, arg.FileID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Version{}
	for rows.Next() {
		var i Version
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.Version,
			&i.Sha256,
			&i.Size,
			&i.UploadedBy,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, from_host, to_host, file_path, size, duration_ms, created_at FROM transfers ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListTransfers(ctx context.Context) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromHost,
			&i.ToHost,
			&i.FilePath,
			&i.Size,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersions = `-- name: ListVersions :many
SELECT v.id, v.file_id, v.version, v.sha256, v.size, v.uploaded_by, v.message, v.created_at
FROM versions v
JOIN files f ON f.id = v.file_id
WHERE (?1 IS NULL OR v.file_id  =    ?1)
  AND (?2  IS NULL OR f.path LIKE ?2 || '%')
ORDER BY f.path ASC, v.version DESC
`

type ListVersionsParams struct {
	FileID interface{} `json:"file_id"`
	Prefix interface{} `json:"prefix"`
}

// ListVersions is the single entry point for querying versions.
// Pass NULL for any filter you want to ignore.
// file_id: versions for a single file
// prefix : versions for all files whose path starts with prefix
// Both can be set at once to scope to a file within a prefix.
func (q *Queries) ListVersions(ctx context.Context, arg ListVersionsParams) ([]Version, error) {
	rows, err := q.db.QueryContext(ctx, listVersions, arg.FileID, arg.Prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Version{}
	for rows.Next() {
		var i Version
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.Version,
			&i.Sha256,
			&i.Size,
			&i.UploadedBy,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneOldVersions = `-- name: PruneOldVersions :exec
DELETE FROM versions
WHERE file_id = ?
  AND version < ?
`

type PruneOldVersionsParams struct {
	FileID  string `json:"file_id"`
	Version int64  `json:"version"`
}

func (q *Queries) PruneOldVersions(ctx context.Context, arg PruneOldVersionsParams) error {
	_, err := q.db.ExecContext(ctx, pruneOldVersions, arg.FileID, arg.Version)
	return err
}

const rollbackToVersion = `-- name: RollbackToVersion :exec
DELETE FROM versions
WHERE file_id = ?
  AND version > ?
`

type RollbackToVersionParams struct {
	FileID  string `json:"file_id"`
	Version int64  `json:"version"`
}

func (q *Queries) RollbackToVersion(ctx context.Context, arg RollbackToVersionParams) error {
	_, err := q.db.ExecContext(ctx, rollbackToVersion, arg.FileID, arg.Version)
	return err
}

const snapshotVersion = `-- name: SnapshotVersion :one
INSERT INTO versions (file_id, version, sha256, size, uploaded_by, message)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, file_id, version, sha256, size, uploaded_by, message, created_at
`

type SnapshotVersionParams struct {
	FileID     string `json:"file_id"`
	Version    int64  `json:"version"`
	Sha256     string `json:"sha256"`
	Size       int64  `json:"size"`
	UploadedBy string `json:"uploaded_by"`
	Message    string `json:"message"`
}

func (q *Queries) SnapshotVersion(ctx context.Context, arg SnapshotVersionParams) (Version, error) {
	row := q.db.QueryRowContext(ctx, snapshotVersion,
		arg.FileID,
		arg.Version,
		arg.Sha256,
		arg.Size,
		arg.UploadedBy,
		arg.Message,
	)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Version,
		&i.Sha256,
		&i.Size,
		&i.UploadedBy,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}
