// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package db

import (
	"context"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (from_host, to_host, filename, size, duration_ms)
VALUES (?, ?, ?, ?, ?)
RETURNING id, from_host, to_host, filename, size, duration_ms, created_at
`

type CreateTransferParams struct {
	FromHost   string `json:"from_host"`
	ToHost     string `json:"to_host"`
	Filename   string `json:"filename"`
	Size       int64  `json:"size"`
	DurationMs int64  `json:"duration_ms"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.FromHost,
		arg.ToHost,
		arg.Filename,
		arg.Size,
		arg.DurationMs,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromHost,
		&i.ToHost,
		&i.Filename,
		&i.Size,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const createVersion = `-- name: CreateVersion :one
INSERT INTO versions (file_id, blob_path, sha256, size, uploaded_by)
VALUES (?, ?, ?, ?, ?)
RETURNING id, file_id, blob_path, sha256, size, uploaded_by, created_at
`

type CreateVersionParams struct {
	FileID     string `json:"file_id"`
	BlobPath   string `json:"blob_path"`
	Sha256     string `json:"sha256"`
	Size       int64  `json:"size"`
	UploadedBy string `json:"uploaded_by"`
}

func (q *Queries) CreateVersion(ctx context.Context, arg CreateVersionParams) (Version, error) {
	row := q.db.QueryRowContext(ctx, createVersion,
		arg.FileID,
		arg.BlobPath,
		arg.Sha256,
		arg.Size,
		arg.UploadedBy,
	)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.BlobPath,
		&i.Sha256,
		&i.Size,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, from_host, to_host, filename, size, duration_ms, created_at FROM transfers
ORDER BY created_at DESC
`

func (q *Queries) ListTransfers(ctx context.Context) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromHost,
			&i.ToHost,
			&i.Filename,
			&i.Size,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionsForFile = `-- name: ListVersionsForFile :many
SELECT id, file_id, blob_path, sha256, size, uploaded_by, created_at FROM versions
WHERE file_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListVersionsForFile(ctx context.Context, fileID string) ([]Version, error) {
	rows, err := q.db.QueryContext(ctx, listVersionsForFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Version{}
	for rows.Next() {
		var i Version
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.BlobPath,
			&i.Sha256,
			&i.Size,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
