// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type File struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Language    string `json:"language"`
	Size        int64  `json:"size"`
	BlobPath    string `json:"blob_path"`
	Sha256      string `json:"sha256"`
	UploadedBy  string `json:"uploaded_by"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type FileTag struct {
	FileID string `json:"file_id"`
	TagID  int64  `json:"tag_id"`
}

type FilesFt struct {
	FileID      string `json:"file_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Content     string `json:"content"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Transfer struct {
	ID         int64  `json:"id"`
	FromHost   string `json:"from_host"`
	ToHost     string `json:"to_host"`
	Filename   string `json:"filename"`
	Size       int64  `json:"size"`
	DurationMs int64  `json:"duration_ms"`
	CreatedAt  string `json:"created_at"`
}

type Version struct {
	ID         int64  `json:"id"`
	FileID     string `json:"file_id"`
	BlobPath   string `json:"blob_path"`
	Sha256     string `json:"sha256"`
	Size       int64  `json:"size"`
	UploadedBy string `json:"uploaded_by"`
	CreatedAt  string `json:"created_at"`
}
