// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Blob struct {
	Sha256    string `json:"sha256"`
	Size      int64  `json:"size"`
	RefCount  int64  `json:"ref_count"`
	CreatedAt string `json:"created_at"`
}

type File struct {
	ID          string `json:"id"`
	Path        string `json:"path"`
	FileName    string `json:"file_name"`
	Description string `json:"description"`
	Language    string `json:"language"`
	Size        int64  `json:"size"`
	Sha256      string `json:"sha256"`
	UploadedBy  string `json:"uploaded_by"`
	Version     int64  `json:"version"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type FileTag struct {
	FileID string `json:"file_id"`
	TagID  int64  `json:"tag_id"`
}

type FilesFt struct {
	FileID      string `json:"file_id"`
	Path        string `json:"path"`
	Description string `json:"description"`
	Content     string `json:"content"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Transfer struct {
	ID         int64  `json:"id"`
	FromHost   string `json:"from_host"`
	ToHost     string `json:"to_host"`
	FilePath   string `json:"file_path"`
	Size       int64  `json:"size"`
	DurationMs int64  `json:"duration_ms"`
	CreatedAt  string `json:"created_at"`
}

type Version struct {
	ID         int64  `json:"id"`
	FileID     string `json:"file_id"`
	Version    int64  `json:"version"`
	Sha256     string `json:"sha256"`
	Size       int64  `json:"size"`
	UploadedBy string `json:"uploaded_by"`
	Message    string `json:"message"`
	CreatedAt  string `json:"created_at"`
}
