// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
	"strings"
)

const addTagToFile = `-- name: AddTagToFile :exec
INSERT OR IGNORE INTO file_tags (file_id, tag_id)
VALUES (?, ?)
`

type AddTagToFileParams struct {
	FileID string `json:"file_id"`
	TagID  int64  `json:"tag_id"`
}

func (q *Queries) AddTagToFile(ctx context.Context, arg AddTagToFileParams) error {
	_, err := q.db.ExecContext(ctx, addTagToFile, arg.FileID, arg.TagID)
	return err
}

const addTagToFilesByPrefix = `-- name: AddTagToFilesByPrefix :exec
INSERT OR IGNORE INTO file_tags (file_id, tag_id)
SELECT f.id, ? FROM files f WHERE f.path LIKE ? || '%'
`

type AddTagToFilesByPrefixParams struct {
	TagID   int64   `json:"tag_id"`
	Column2 *string `json:"column_2"`
}

func (q *Queries) AddTagToFilesByPrefix(ctx context.Context, arg AddTagToFilesByPrefixParams) error {
	_, err := q.db.ExecContext(ctx, addTagToFilesByPrefix, arg.TagID, arg.Column2)
	return err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name FROM tags WHERE name = ? LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, name FROM tags ORDER BY name ASC
`

func (q *Queries) ListAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForFiles = `-- name: ListTagsForFiles :many
SELECT ft.file_id, t.id, t.name
FROM tags t
JOIN file_tags ft ON ft.tag_id = t.id
WHERE ft.file_id IN (/*SLICE:ids*/?)
ORDER BY ft.file_id, t.name ASC
`

type ListTagsForFilesRow struct {
	FileID string `json:"file_id"`
	ID     int64  `json:"id"`
	Name   string `json:"name"`
}

// ListTagsForFiles returns tags for one or more files in a single query.
// Returns (file_id, tag id, tag name) so the caller can group by file_id.
// Pass a slice with a single element to query tags for one file.
func (q *Queries) ListTagsForFiles(ctx context.Context, ids []string) ([]ListTagsForFilesRow, error) {
	query := listTagsForFiles
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForFilesRow{}
	for rows.Next() {
		var i ListTagsForFilesRow
		if err := rows.Scan(&i.FileID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllTagsFromFile = `-- name: RemoveAllTagsFromFile :exec
DELETE FROM file_tags WHERE file_id = ?
`

func (q *Queries) RemoveAllTagsFromFile(ctx context.Context, fileID string) error {
	_, err := q.db.ExecContext(ctx, removeAllTagsFromFile, fileID)
	return err
}

const removeAllTagsFromFilesByPrefix = `-- name: RemoveAllTagsFromFilesByPrefix :exec
DELETE FROM file_tags
WHERE file_id IN (SELECT id FROM files WHERE path LIKE ? || '%')
`

func (q *Queries) RemoveAllTagsFromFilesByPrefix(ctx context.Context, dollar_1 *string) error {
	_, err := q.db.ExecContext(ctx, removeAllTagsFromFilesByPrefix, dollar_1)
	return err
}

const removeTagFromFile = `-- name: RemoveTagFromFile :exec
DELETE FROM file_tags
WHERE file_id = ? AND tag_id = ?
`

type RemoveTagFromFileParams struct {
	FileID string `json:"file_id"`
	TagID  int64  `json:"tag_id"`
}

func (q *Queries) RemoveTagFromFile(ctx context.Context, arg RemoveTagFromFileParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromFile, arg.FileID, arg.TagID)
	return err
}

const removeTagFromFilesByPrefix = `-- name: RemoveTagFromFilesByPrefix :exec
DELETE FROM file_tags
WHERE tag_id = ?
  AND file_id IN (SELECT id FROM files WHERE path LIKE ? || '%')
`

type RemoveTagFromFilesByPrefixParams struct {
	TagID   int64   `json:"tag_id"`
	Column2 *string `json:"column_2"`
}

func (q *Queries) RemoveTagFromFilesByPrefix(ctx context.Context, arg RemoveTagFromFilesByPrefixParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromFilesByPrefix, arg.TagID, arg.Column2)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = excluded.name
RETURNING id, name
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
