// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
)

const addTagToFile = `-- name: AddTagToFile :exec
INSERT INTO file_tags (file_id, tag_id)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddTagToFileParams struct {
	FileID string `json:"file_id"`
	TagID  int64  `json:"tag_id"`
}

func (q *Queries) AddTagToFile(ctx context.Context, arg AddTagToFileParams) error {
	_, err := q.db.ExecContext(ctx, addTagToFile, arg.FileID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = excluded.name
RETURNING id, name
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name FROM tags WHERE name = ? LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listFilesForTag = `-- name: ListFilesForTag :many
SELECT f.id, f.path, f.file_name, f.dir_id, f.dir_prefix, f.description, f.language, f.size, f.blob_path, f.sha256, f.uploaded_by, f.version, f.created_at, f.updated_at FROM files f
JOIN file_tags ft ON ft.file_id = f.id
JOIN tags t ON t.id = ft.tag_id
WHERE t.name = ?
ORDER BY f.created_at DESC
`

func (q *Queries) ListFilesForTag(ctx context.Context, name string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesForTag, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.FileName,
			&i.DirID,
			&i.DirPrefix,
			&i.Description,
			&i.Language,
			&i.Size,
			&i.BlobPath,
			&i.Sha256,
			&i.UploadedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForFile = `-- name: ListTagsForFile :many
SELECT t.id, t.name FROM tags t
JOIN file_tags ft ON ft.tag_id = t.id
WHERE ft.file_id = ?
ORDER BY t.name
`

func (q *Queries) ListTagsForFile(ctx context.Context, fileID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllTagsFromFile = `-- name: RemoveAllTagsFromFile :exec
DELETE FROM file_tags WHERE file_id = ?
`

func (q *Queries) RemoveAllTagsFromFile(ctx context.Context, fileID string) error {
	_, err := q.db.ExecContext(ctx, removeAllTagsFromFile, fileID)
	return err
}

const removeTagFromFile = `-- name: RemoveTagFromFile :exec
DELETE FROM file_tags
WHERE file_id = ? AND tag_id = ?
`

type RemoveTagFromFileParams struct {
	FileID string `json:"file_id"`
	TagID  int64  `json:"tag_id"`
}

func (q *Queries) RemoveTagFromFile(ctx context.Context, arg RemoveTagFromFileParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromFile, arg.FileID, arg.TagID)
	return err
}
